mysql:
  ip: 127.0.0.1
  port: 3306
  user: root
  pwd: root
  db: workapp
  charset: utf8mb4,utf8
  MaxIdleTime: 30   #最大空闲连接时间(秒)
  MaxIdleConns: 10  #空闲连接池最大数量
  MaxOpenConns: 100 #最大打开的连接数
  MaxLifetime: 1    #连接可复用的最长时间(小时)
redis:
  addr: 127.0.0.1:3309
  password: ""
  db: 0