app:
  addr: 127.0.0.1:8080
  gin_mode: debug #debug|release|test
  static_path: static
  template_path: internal/view/**/*
  nologurl: static
session:
  sessionId: PHPSESSIONID
  authentication: qwer123456                    #用于身份验证
  encryption: d41d8cd98f00b204e9800998ecf8427e  #用于加密cookie中的数据 32位AES-256 24位AAES-192 16位AES-128
cookie:
  Path: /
  Domain:
  MaxAge: 604800 #一周（秒）
  Secure: false
  HttpOnly: true
  SameSite: 2 #2:Lax 3:Strict 4:None
upload:
  upload_path: upload
  upload_maxsize: 100 #请求数据最大容量(MB)